const fontArray: string[] = [
	"Tengwar", "Knob", "JS Bracket Letters", "Doom", "Banner3", "Madrid", "Pagga", "Shadow", "Runic",
	"AMC Thin", "Small Script", "AMC Tubes", "Patorjk's Cheese", "AMC Slash", "Stop", "Goofy", "Bell",
	"Morse2", "Bright", "AMC Slider", "Nipples", "Ogre", "Shaded Blocky", "Varsity", "Gradient", "Marquee",
	"Swan", "Tubular", "Cards", "Rounded", "Digital", "Caligraphy", "Efti Water", "Patorjk - HeX",
	"Star Strips", "Cyberlarge", "AMC Razor2", "Keyboard", "Horizontal Right", "Mirror", "Horizontal Left",
	"Puzzle", "BlurVision ASCII", "Wavy", "3D - ASCII", "Diamond", "DANC4", "Crawford2", "Relief", "Block",
	"Sweet", "Linux", "SL Script", "Cygnet", "Ghost", "Rotated", "Pyramid", "Standard", "Poison",
	"3D Diagonal", "Broadway KB", "JS Cursive", "Chiseled", "Contrast", "Def Leppard", "Star Wars",
	"Reverse", "Efti Italic", "Big Money - ne", "5 Line Oblique", "Cricket", "Big Money - nw", "Hex", "Merlin1",
	"Stellar", "Braced", "Thick", "Efti Chess", "Cursive", "Dancing Font", "Banner4", "Stforek",
	"Fraktur", "Larry 3D", "Alligator", "Heart Left", "Jacky", "Rowan Cap", "Binary", "Rammstein", "Diet Cola",
	"Efti Wall", "Glenyn", "Big Chief", "Georgia11", "The Edge", "Hollywood", "Small Tengwar",
	"Isometric4", "Coinstak", "Muzzle", "Crazy", "Isometric3", "Nancyj-Underlined", "Relief2", "Mini",
	"Pepper", "Graceful", "Catwalk", "Bloody", "Double Shorts", "O8", "Mnemonic", "Crawford", "Santa Clara",
	"Filter", "Stronger Than All", "Straight", "Big Money - se", "OS2", "DOS Rebel", "Short", "Heart Right",
	"Slant", "Fire Font - k", "Lil Devil", "Mshebrew210", "B1FF", "Fun Faces", "ICL - 1900", "Rectangles",
	"Train", "Two Point", "Hieroglyphs", "Lockergnome", "Bulbhead", "Merlin2", "Four Tops",
	"Avatar", "3x5", "Konto Slant", "Dr Pepper", "Delta Corps Priest 1", "Pawp", "JS Stick Letters", "Broadway",
	"Barbwire", "Shimrod", "Stampatello", "Ticks", "Jazmine", "Chunky", "Twisted", "Basic", "Fun Face", "Gothic",
	"Small Slant", "AMC 3 Line", "Colossal", "Lean", "Serifcap", "Morse", "Elite",
	"Bear", "Modular", "Line Blocks", "Contessa", "Old Banner", "Caligraphy2", "Maxfour", "JS Block Letters",
	"Pebbles", "THIS", "Isometric1", "Fuzzy", "Term", "Kban", "Ivrit", "Three Point", "Larry 3D 2", "Univers",
	"Stampate", "RubiFont", "Test1", "Alligator2", "Speed", "Efti Robot", "Stacey", "Swamp Land", "Peaks Slant",
	"Greek", "Mike", "JS Capital Curves", "Big", "Rot13", "Soft", "Tinker - Toy",
	"Thorned", "Moscow", "AMC Razor", "Small Caps", "Electronic", "ANSI Regular", "Acrobatic", "Ghoulish",
	"Banner", "Tsalagi", "Small Isometric1", "Bubble", "S Blood", "Bolger", "Efti Font", "Nancyj - Fancy",
	"AMC AAA01", "Puffy", "Weird", "Fender", "4Max", "Double", "Tiles", "Impossible", "NV Script", "Blocks",
	"Decimal", "Alpha", "Invita", "Fire Font - s", "Tanja", "Doh", "Roman", "NScript", "Red Phoenix",
	"Small Keyboard", "Italic", "Small", "Stick Letters", "Cola", "Cosmike", "Slide", "Rozzo",
	"Ticks Slant", "Graffiti", "Wow", "3 - D", "Sub - Zero", "Slant Relief", "Epic", "Small Shadow", "Dot Matrix",
	"DiamFont", "Whimsy", "Letters", "Small Poison", "Tombstone", "Flower Power", "Octal",
	"Nancyj - Improved", "1Row", "Cosmike2", "Konto", "Spliff", "Katakana", "ANSI Shadow", "Computer", "Henry 3D",
	"Bigfig", "Banner3 - D", "AMC Neko", "AMC Untitled", "Calvin S", "Efti Piti", "Isometric2",
	"Big Money-sw", "Georgi16", "ASCII New Roman", "Jerusalem", "Flipped", "NT Greek", "Alphabet", "Benjamin",
	"Thin", "Cybermedium", "LCD", "Arrows", "DWhistled", "USA Flag", "Trek", "Runyc", "Peaks",
	"AMC 3 Liv1", "Cybersmall", "Nancyj", "Script", "Wet Letter",
]
export { fontArray };
